##
## Makefile for raytracer in /home/simon_o//raytracer-2017-simon_o
##
## Made by antoine simon
## Login   <simon_o@epitech.net>
##
## Started on  Mon Apr 29 09:02:14 2013 antoine simon
## Last update Mon Apr 29 19:50:14 2013 florian corradin
##

NAME	= rt

SRC	= main.c \
	inter.c \
	calc_all.c \
	my_putstr.c \
	resolver.c \
	get_next_line.c \
	tools.c

OBJ	= $(SRC:.c=.o)

all:	$(NAME)

$(NAME):	$(OBJ)
	cc $(OBJ) -o $(NAME) -lmlx -lXext -lX11 -lm -Wextra -pedantic -ansi -Wall -lm

clean:
	rm -f $(OBJ)

fclean:
	rm -f $(OBJ)
	rm -f $(NAME)

re:	fclean all